# Rime default settings
# encoding: utf-8

config_version: "0.40"

schema_list:
  #  - schema: luna_pinyin
  #  - schema: luna_pinyin_simp
  #  - schema: luna_pinyin_fluency
  #  - schema: bopomofo
  #  - schema: bopomofo_tw
  #  - schema: cangjie5
  #  - schema: stroke
  #  - schema: terra_pinyin
  - schema: luna_pinyin_simp # 朙月拼音 简化字模式
  - schema: luna_pinyin # 朙月拼音
  - schema: luna_pinyin_tw # 朙月拼音 臺灣正體模式
  - schema: terra_pinyin # 地球拼音 dì qiú pīn yīn
  - schema: bopomofo # 注音
  - schema: bopomofo_tw # 注音 臺灣正體模式
  - schema: jyutping # 粵拼
  - schema: cangjie5 # 倉頡五代
  - schema: cangjie5_express # 倉頡 快打模式
  - schema: quick5 # 速成
  - schema: wubi86 # 五笔86
  - schema: wubi_pinyin # 五笔拼音混合輸入
  - schema: double_pinyin # 自然碼雙拼
  - schema: double_pinyin_mspy # 微軟雙拼
  - schema: double_pinyin_abc # 智能ABC雙拼
  - schema: double_pinyin_flypy # 小鶴雙拼
  - schema: wugniu # 吳語上海話（新派）
  - schema: wugniu_lopha # 吳語上海話（老派）
  - schema: sampheng # 中古漢語三拼
  - schema: zyenpheng # 中古漢語全拼
  - schema: ipa_xsampa # X-SAMPA 國際音標
  - schema: emoji # emoji表情

switcher:
  caption: 〔方案選單〕
  hotkeys:
    - Control+grave
    - Control+Shift+grave
    - F4
  save_options:
    - full_shape
    - ascii_punct
    - simplification
    - extended_charset
    - zh_hant
    - zh_hans
    - zh_hant_tw
  fold_options: true
  abbreviate_options: true
  option_list_separator: "／"

menu:
  page_size: 5

punctuator:
  full_shape:
    __include: punctuation:/full_shape
  half_shape:
    __include: punctuation:/half_shape

key_binder:
  bindings:
    __patch:
      - key_bindings:/emacs_editing
      - key_bindings:/move_by_word_with_tab
      - key_bindings:/paging_with_minus_equal
      - key_bindings:/paging_with_comma_period
      - key_bindings:/numbered_mode_switch

recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: inline_ascii
    Shift_R: commit_text
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
    Eisu_toggle: clear
